import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { siteConfig } from "@/config/site";

const faqData = [
  {
    question: "What are CRE AI tools?",
    answer: `CRE AI tools are software platforms that leverage artificial intelligence to enhance decision-making and automate processes within the Commercial Real Estate sector. They provide insights into market trends, property valuation, investment analysis, and operational efficiency. These tools are essential for maintaining a competitive edge in today's market.`
  },
  {
    question: "Which CRE AI tool is best for beginners?",
    answer: `For those new to CRE AI, starting with a tool that has a user-friendly interface and strong customer support is key. Many platforms offer free trials or demos, which are a great way to explore the features and find the best fit for your business needs without a significant initial investment.`
  },
  {
    question: "What's the difference between traditional CRE software and AI-powered tools?",
    answer: `Traditional CRE software typically offers data storage and management functionalities. AI-powered tools go a step further by providing predictive analytics, automated workflows, and data-driven insights that help you forecast market changes, identify investment opportunities, and optimize your portfolio performance.`
  },
  {
    question: "Do I need a data scientist to use CRE AI tools?",
    answer: `No, most modern CRE AI tools are designed to be user-friendly and do not require a background in data science. They often feature intuitive dashboards and automated reporting, making it easy for real estate professionals to access and understand the insights generated by the AI.`
  },
  {
    question: "How much do CRE AI tools typically cost?",
    answer: `The cost of CRE AI tools can vary widely, from affordable monthly subscriptions for specific features to comprehensive enterprise-level packages. Pricing is often based on the number of users, the volume of data processed, or the specific functionalities included.`
  },
  {
    question: "What metrics are most important when evaluating CRE AI tools?",
    answer: `When evaluating CRE AI tools, focus on metrics that align with your business goals. Key areas to consider include the accuracy of predictive models, the level of automation provided, the ease of integration with your existing systems, and the quality of customer support.`
  },
  {
    question: "Can I integrate multiple CRE AI tools?",
    answer: `Yes, it is often beneficial to use a combination of CRE AI tools to cover different aspects of your business, such as property management, investment analysis, and marketing. Look for tools with robust API capabilities to ensure seamless data flow between platforms.`
  },
  {
    question: "How do I ensure data security with CRE AI tools?",
    answer: `Data security is a top priority for CRE AI tool providers. They typically employ advanced encryption, regular security audits, and comply with industry standards to protect your sensitive information. Always review a tool's security and compliance documentation before making a commitment.`
  }
];

export function FAQ() {
  return (
    <section className="py-16 md:py-24 bg-muted/30">
      <div className="container px-6">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4">
            Frequently Asked Questions
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto">
            Get answers to common questions about {siteConfig.categoryName.toLowerCase()} and how to choose the right solution for your needs.
          </p>
        </div>
        
        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="space-y-0">
            {faqData.map((faq, index) => (
              <AccordionItem 
                key={index} 
                value={`item-${index}`}
                className="border-0 border-b border-neutral-200 last:border-b-0"
              >
                <AccordionTrigger className="text-left hover:no-underline py-6 px-0 font-medium text-neutral-900 hover:text-neutral-600 transition-colors">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="pb-6 px-0 text-neutral-600 leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
        
      </div>
    </section>
  );
} 